---
- name: Install and start httpd package
  hosts: Webserver
  vars:
    web_content: |
      Welcome to {{ ansible_hostname }}
  tasks:
    - name: Install the httpd package.
      yum:
        name: httpd
        state: present
    - name: Start the httpd package.
      service:
       name: httpd
       state: started
       enabled: yes
    - name: Create a custom index.html file.
      copy:
        dest: /var/www/html/index.html
        content: "{{ web_content }}"
        owner: apache
        group: apache
        mode: '0644'
      notify:
        - Restart httpd
    - name: Allow HTTP service through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        zone: public
    - name: Reload firewalld to apply changes
      command: firewall-cmd --reload
  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
